language: go
go: 
 - 1.8
 - 1.9
install:
 - go get -v
 - go get -v github.com/smartystreets/goconvey
 - go get -u github.com/alecthomas/gometalinter
script:
 - gometalinter --install
 - gometalinter --config=./gometalinter.json --vendor ./...
